name: CI

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: mypay
          MYSQL_PASSWORD: mypay@123
          MYSQL_DATABASE: mypay

    steps:
    - uses: actions/checkout@v1
    - uses: tifabio/lumen-phpunit-action@master